### ISSUE TITLE
Woven tests can generate an InvalidProgramExceptions, depending on build configuration

### ISSUE THREAD

**Issue by DaleStan** [Fody/AssertMessage#12]
The attached project contains two tests. When the project is built in debug mode, TestMethod1 will fail by throwing an InvalidProgramException, and TestMethod2 will pass. In release mode, the results swap. TestMethod1 passes, but TestMethod2 throws an InvalidProgramException.

Both tests should pass regardless of build configuration.

[InvalidProgramException.zip](https://github.com/Fody/AssertMessage/files/2425338/InvalidProgramException.zip)

I'm building in VS2017, targeting .NET Framework 4.7.2. I'm using Fody 3.2.4, AssertMessage.Fody 2.0.1, and MSTest V2 1.3.2.

**Comment by SimonCropp** [comment]
Did you make any attempt to fix it?

**Comment by DaleStan** [comment]
Well, I think I found the cause, but I have no idea which project is responsible for the fix. Both involve branch instructions that didn't get fixed up properly.

In the debug version of Method1, there's a br.s that branches forward 0x60 bytes. After inserting the new ldstr instructions, it wants to branch forward 0x88 bytes, but it doesn't get replaced with a br. Release works because the compiler emits ret, instead of br.s.

In the release version of Method2, there's a brfalse.s that jumps to the "call Assert::Fail()" instruction. AssertMessage changes the call to "call Assert.Fail(string)", and inserts a ldstr before the call, but the brfalse.s still jumps to the call, not the ldstr. Debug works because the brfalse.s jumps to a nop before the call, instead of jumping to the call.

**Comment by SimonCropp** [comment]
your best bet is to start by adding a failing unit test. then step through the code to see what injects the invalid code

**Comment by DaleStan** [comment]
I have what I think is a decent idea for how to fix the branch-to-call issue, but nothing looks remotely pretty for the no-longer-short-branch detection and conversion.

AssertMessage doesn't touch the 0x60-to-0x88 byte short branch at all. It inserts instructions between the branch and its target, but it leaves both the branch and its target alone. I suspect Mono.Cecil emits the bogus offset. Is this something that needs to be taken up with Mono.Cecil?

I see the modified collection of instructions, including the branch instruction and its target, but I don't see a good way to ask how far the branch is from its target. I could manually recalculate all the offsets, but that's all sorts of ugly.

**Comment by SimonCropp** [comment]
i think i fixed the debug one with some macro manipulation https://github.com/Fody/AssertMessage/pull/13

the release one still seems to be failing. feel free to have a look into it

**Comment by DaleStan** [comment]
That macro manipulation in #13 is so much better than the mess I was going to make of that.

Also, sigh. Turns out trys and switches were another thing that didn't work, for basically the same reason. I think everything is working in #14. I've run the whole test project that I simplified down to that repro, and they all pass now.

**Comment by SimonCropp** [comment]
this should now be deployed, pending nuget updating its index. thanks for your help
