### ISSUE TITLE
Won't work for tests projects without generated .pdb file

### ISSUE THREAD

**Issue by Ethenyl** [Fody/AssertMessage#2]
Hi there,

Just a little issue I ran into while working on a big project.

I have a solution with 10 projects, 3 tests, 1 version control, 1 CLI (main project) and the other are business related.

Everything was building fine in debug but was going nuts in Release mode, I've spent a few hours to refactor my tests, clean them up, tests them one by one.

And after unpacking the master of AssertMessage, I found that the .pdb file associated with the tests are used by AM.

I checked 2 of my 3 test projects, both weren't generating the required files, I must have change that behavior a while ago but I never noticed any problem with that.

I changed them to generate the files again and this time everything went well, no hiccups !

I don't know if I was doing something wrong, but is it a normal behaviour for AM ?

Thanks for the answer ^^

**Comment by SimonCropp** [comment]
@rjasica thoughts?

**Comment by rjasica** [comment]
The pdb files is required for this plugin. 
I changed exception message to be more descriptive.
I also added info in readme.
