### ISSUE TITLE
How to run tests from AssemblyToProcess/MstestTests.cs?

### ISSUE THREAD

**Issue by MNF** [Fody/AssertMessage#5]
I've cloned Fody/AssertMessage and tried to run tests from AssemblyToProcess/MstestTests.cs.

I've added [TestClass]/[TestMethod] attributes and run them, but they do not have messages appended. 
I can see that Tests\MstestTests.cs run successfully, but not when I run them directly. 
Does it mean, that Fody weaver is not invoked, when I run unit tests from AssemblyToProcess? How can I force it to invoke? 
Update: I've noticed, that when I rebuild the whole solution, Fody executes for AssemblyToProcess.dll, but when I rebuild only AssemblyToProcess project, Fody is not called.
In https://github.com/Fody/Fody/wiki/InSolutionWeaving it's suggested to create project named 'Weavers', but the repository already has folder "Fody" with the similar purpose.
Note, that I am new to Fody and likely missed something obvious.

**Comment by rjasica** [comment]
The file AssemblyToProcess/MstestTests.cs is only placeholder. Please run test in Tests/MstestTests.cs to check if MsTest works correctly.
