### ISSUE TITLE
Update to Fody Version 2

### ISSUE THREAD

**Issue by jasonwoods-7** [Fody/AssertMessage#6]
I was trying to update my Fody add-in to use Fody Version 2 for jasonwoods-7/Vandelay#2, but I'm using AssertMessage in my project.

I tried looking into doing a PR for AssertMessage, but I wasn't sure how to update it since SequencePoint is no longer a member of the Instruction object in the new Mono.Cecil.

**Comment by jasonwoods-7** [comment]
I actually found out what change needs to be made, but currently, because of a bug in Fody, the Stamp.Fody weaver is failing.  I added PR Fody/Fody#304 to fix the issue running Stamp.Fody.

Once that has been merged, I can add a PR for this issue.

**Comment by rjasica** [comment]
Thanks for reporting issue. Package 1.1.0 contains fix for it.
