### ISSUE TITLE
Can generate an InvalidProgramException in cases when Assert.Fail is used in close proximity to switch

### ISSUE THREAD

**Issue by DaleStan** [Fody/AssertMessage#7]
I've added AssertMessage.Fody to one of our unit test projects, and have discovered that constructs where there's an `Assert.Fail()` (with no argument) near a `switch`, instead of throwing an `AssertFailedException` will throw an `InvalidProgramException`. I've attached a small reproducer; the two tests fail (throw `InvalidProgramException`) in both Debug and Release mode.

Removing &lt;AssertMessage /> from FodyWeavers.xml or adding messages to the two `Assert.Fail()` calls will make the tests pass (throw `AssertFailedException`) again.

**Comment by DaleStan** [comment]
... Apparently I didn't attach the reproducer. Sorry about that; here it is.
[AssertMessageTest.zip](https://github.com/Fody/AssertMessage/files/1009655/AssertMessageTest.zip)

**Comment by DaleStan** [comment]
Actually, false alarm. It appears that updating to Fody 2.0.9 fixes this, both in this reproducer and in our production tests.

**Comment by SimonCropp** [comment]
closing this as stale. if it is still an problem please raise a new issue
